name: Deploy

on:
  workflow_call:
    inputs:
      channelId:
        type: string
        required: false
    outputs:
      details_url:
        value: ${{ jobs.deploy.outputs.details_url }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      details_url: ${{ steps.firebase.outputs.details_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: build
          path: build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        id: firebase
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MARGNI_DOUGH }}'
          channelId: ${{ inputs.channelId }}
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
